[package]
name = "cpr"
version = "0.1.0"
edition = "2021"

[dependencies]
aes = "0.8.2"
base64 = "~0.13"
hex = "~0.4"
pico-args = "0.5.0"
rand = "0.8.5"
sha1 = "0.10.5"
reqwest = { version = "0.11.13", features = ["blocking"] }
