---
version: "3"

vars:
  STATIC_URL: "https://cryptopals.com/static/challenge-data"

tasks:
  default:
    - task: all

  up:
    desc: Runs nix-shell and task runner. Assumes taskfile installed locally.
    cmds:
      - nix-shell --run "task"

  all:
    desc: Format, test, and lint code.
    deps:
      - data
      - test
      - fmt

  data:
    desc: Set up test data.
    cmds:
      - task: download
        vars: { FILE: 4.txt }
      - task: download
        vars: { FILE: 6.txt }
      - task: download
        vars: { FILE: 7.txt }
      - task: download
        vars: { FILE: 8.txt }

  download:
    desc: Download test data.
    label: "download-{{ .FILE }}"
    cmds:
      - mkdir -p ./data
      - wget -q -O "./data/{{ .FILE }}" "{{ .STATIC_URL }}/{{ .FILE }}"
    status:
      - test -f "./data/{{ .FILE }}"

  fmt:
    desc: Format and lint code.
    cmds:
      - cargo fmt
      - cargo fix --allow-dirty --allow-staged
      - cargo clippy --fix --allow-dirty --allow-staged

  test:
    desc: Run unit tests.
    cmds:
      - cargo test

  watch:
    desc: Watch and run unit tests.
    cmds:
      - cargo watch -x test
