#!/usr/bin/env bash
GRN='\e[0;32m'
RED='\e[0;31m'
RST='\e[0m'

echo -e "$GRN[*]$RST cargo check"
cargo check --quiet
CHECK=$?
if [ $CHECK -ne 0 ]; then
    echo -e "$RED[!]$RST code failed to compile, aborting commit"
    exit 1
fi

echo -e "$GRN[*]$RST cargo test"
cargo test --quiet >/dev/null
TEST=$?
if [ $TEST -ne 0 ]; then
    echo -e "$RED[!]$RST tests failed, aborting commit"
    exit 1
fi

echo -e "$GRN[*]$RST cargo fmt"
cargo fmt --check
FMT=$?
if [ $FMT -ne 0 ]; then
    echo -e "$RED[!]$RST code is not formatted, aborting commit and formatting code"
    cargo fmt
    exit 1
fi

echo -e "$GRN[*]$RST cargo clippy"
cargo clippy
FMT=$?
if [ $FMT -ne 0 ]; then
    echo -e "$RED[!]$RST clippy failed, aborting commit and fixing code"
    cargo clippy --fix --allow-dirty
    exit 1
fi
